export const theme = {
    light: {
        bg_primary: 'white',
        main_white: 'white',
        text_primary: 'rgba(0,0,0,.8)',
        text_black: 'rgba(0,0,0,1)',
        text_white_2: 'rgba(0,0,0,.7)',
        text_white_3: 'rgba(0,0,0,.5)',
        text_semi_black: '#000000e4',
        text_dark_blue: '#00376b',
        text_gray_1: '#b5b3b3',
        text_gray_2: '#f4f3f3',
        primary_2: 'gray',
        primary_3: '#DBDBDB',
        blue: '#5295F6',
        blue_2: '#5295F6',
        border: '#DBDBDB',
        input: {
            color: 'black',
            border: '#DBDBDB',
        },
        btn: {
            color: '#1db9dc',
        },
    },
    dark: {
        bg_primary: ' rgba(0,0,0,1)',
        text_primary: 'white',
        main_white: 'white',
        text_black: 'black',
        text_white_2: 'rgba(255,255,255,.8)',
        text_white_3: 'rgba(255,255,255,.3)',
        text_semi_black: 'white',
        text_gray_1: 'white',
        text_gray_2: 'white',
        primary_2: 'white',
        primary_3: 'black',
        border: 'white',
        blue: 'white',
        blue_2: '#5295F6',
        text_dark_blue: 'white',
        input: {
            color: 'white',
            border: 'white',
        },
        btn: {
            color: 'white',
        },
    },
};
